#linters-settings:
#  govet:
#    # Disable all analyzers.
#    # Default: false
#    disable-all: true
#    # Enable analyzers by name.
#    # (in addition to default:
#    #   appends, asmdecl, assign, atomic, bools, buildtag, cgocall, composites, copylocks, defers, directive, errorsas,
#    #   framepointer, httpresponse, ifaceassert, loopclosure, lostcancel, nilfunc, printf, shift, sigchanyzer, slog,
#    #   stdmethods, stringintconv, structtag, testinggoroutine, tests, timeformat, unmarshal, unreachable, unsafeptr,
#    #   unusedresult
#    # ).
#    # Run `GL_DEBUG=govet golangci-lint run --enable=govet` to see default, all available analyzers, and enabled analyzers.
#    # Default: []
#    enable:
#      - copylocks